### ISSUE TITLE
Pipe quebrado

### ISSUE THREAD

**Issue by 4lnx** [slackjeff/bananapkg#1]
Este erro acontece aleatoriamente, quando o banana é usado em um diretório
diferente da localização do pacote, exemplo:
#pwd
/
#banapkg -i /home/$USER/Downloads/glibc-2.28-1.mz
esta a cada 10 vezes acontece uma.

uma outra forma que acontece o erro mais facilmente quando se usa o operador *
para instalar mais de um pacote com o mesmo comando.
exemplo:
#banapkg -i /home/$USER/Downloads/*.mz

### ERRO:
```
/usr/libexec/banana/core.sh, linha 433:  2386 Pipe quebrado           
tar xvpmf "${packname}" -C /  2387 Erro no barramento  
| tee -a ${dirlist}/"${name_version_build}.list" 1>&4 2>&3
```

**Comment by slackjeff** [comment]
Show, vou dar uma olhada aqui

**Comment by slackjeff** [comment]
Por fins de explicação futuras para outros programadores, o problema acontecia na hora de criar a lista como mencionado. O Comando tee que era responsável por esse processo acabava que aleatoriamente encerrando antes da hora, assim quebrando o comando tar que enviava a saída para um pipe sem saída.
A Resolução foi feita retirando o pipe e adicionando a criação de lista individual. Ficou alguns milissegundos mais lento mas o problema foi resolvido de uma vez.
