### ISSUE TITLE
Erro ao remover pacote - banana apagando arquivos indevidos

### ISSUE THREAD

**Issue by vcatafesta** [slackjeff/bananapkg#10]
Ao remover um pacote com banana -r, este está removendo o diretório no qual foi instalado mesmo que não vazio e tenha outros arquivos que não foram instalados pelo banana.

O exemplo ocorreu ao instalar o httpd apache, no qual removeu toda a árvore do diretório /srv/www  com seus arquivos lá estando.

O único arquivo que deveria remover seria o /srv/www/index.html, que estava no tarball de instalação, porém removeu a pasta /srv/www e todos o restante dos arquivos.

**Comment by vcatafesta** [comment]
No exemplo do apache, normalmente o arquivo padrão index.html é substituído pelo usuário por outro, sendo necessário fazer uma checagem do arquivo antes de remover, para ver se é o mesmo que foi instalado e não outro que foi substituído pelo usuário.

**Comment by vcatafesta** [comment]
Em tempo, o arquivo rm.sh não contém comandos para remoção de qualquer pacote

**Comment by slackjeff** [comment]
Opa! Obrigado pelo report.
Bom, o bug foi resolvido adicionado o diretório srv/www(httpd) no filtro!
Está disponivel na nova versão.
