### ISSUE TITLE
busca do banana usa nome absoluto pacote

### ISSUE THREAD

**Issue by linclord** [slackjeff/bananapkg#11]
Não é um bug propriamente dito, mas o bananapkg não busca por partes dos nomes de pacotes, por exemplo, ao digitar `banana -s chrome` ele não encontra nada, preciso digitar o nome completo do pacote google_chrome.

`root [ ~ ]# banana -V`
`banana Version 2.2.4.6_littlewitchbrown`
`root [ ~ ]# banana -s chrome`
`No packages found with the name of: chrome`
`root [ ~ ]# banana -s google_chrome`
`#------------------------[ FOUND ]----------------------------------------------#`
`[ PACKAGE ]	google_chrome`
`[ VERSION ]	71.0.3578.98`
`[ BUILD   ]	1`
`[ URL     ]	https://www.google.com/chrome/`
`[ DEPS    ]	`
`[ DESC    ]	Google Chrome Web Browser`
` `
`root [ ~ ]#`

**Comment by slackjeff** [comment]
Oi, bom não é um bug mesmo hehe, o banana usa regex/expressão regular para procurar, por padrão ativado, inclusive extendida...
se você usar banana search .*chrome ele vai achar o pacote.
Se você tem o mutt no começo e no meio do pacote exemplo:

**mutt**-xxxxxx
xxxxx-**mutt**

E queira buscar somente o que começa com mutt:

banana search ^mutt
No meio:
banana search .*mutt

**Comment by linclord** [comment]
Ótimo, é que a maioria dos gerenciadores que conheço não funciona assim, não estava sabendo.
Pode fechar o issue então.
