### ISSUE TITLE
/sbin/banana: line 225: : command not found

### ISSUE THREAD

**Issue by Viniciusalopes** [slackjeff/bananapkg#17]
Cenário:
- Instalação limpa da MazonOs a partir da iso [mazon-beta-1.4-3-livecd.iso](http://mazonos.com/releases/)
- Primeiro boot da MazonOs
- Instalação do banana:
`# git clone https://github.com/slackjeff/bananapkg.git && \`
`cd bananapkg && ./install.sh`
---
Ao executar o banana sem parametros, ou com o parametro -h ocorre o erro:
`/sbin/banana: line 225: : command not found`

Problema: a variável $HELP não está declarada.

Solução: declarar $HELP antes da linha 99:
`HELP='_HELP_US'`
ou
`HELP='_HELP_PT'`

Esses valores para a variável $HELP são nomes de funções de `/usr/libexec/banana/help.sh`

Na versão 2.1.4-1 que está no repositório da MazonOs tem esse trecho na linha 64:
`# Qual a linguagem do cabra?`
`[[ "$LANG" = "pt_BR.utf8" ]] && HELP="_HELP_PT" || HELP="_HELP_US"`

**Comment by slackjeff** [comment]
Obrigado vovo! Foi resolvido!!!! s2
