### ISSUE TITLE
Dono e grupo dos pacotes sendo alterados.

### ISSUE THREAD

**Issue by f9kill** [slackjeff/bananapkg#26]
Ao instalar algum pacote com o banana, o **dono** e **grupo** dos diretórios alvos são alteradas para a do usuário padrão.

**Comment by slackjeff** [comment]
Opa, você ja enviou o pull para mim?

**Comment by f9kill** [comment]
No momento eu apenas identifiquei a falha, estou fazendo alguns testes para descobrir como resolvê-la.

**Comment by f9kill** [comment]
slackjeff, eu fiz alguns testes aqui na mazonOS, e descobrir que na verdade o problema estava em alguns pacotes que eu criei. Foi mal.
