### ISSUE TITLE
Adicionar, versão do banana no desc.

### ISSUE THREAD

**Issue by diegosarzi** [slackjeff/bananapkg#3]
Algumas pessoas estão usando o banana antigo para empacotar.
Teria uma forma de colocarmos a versão do banana dentro de desc? Para que assim eu possa ter controle sobre as modificações e empacotamento?
Obrigado

**Comment by slackjeff** [comment]
Opa, você diz só um comentário ou que apareça na impressão das informações do pacote?

**Comment by diegosarzi** [comment]
Um campo dentro de desc com versionbanana='' que já auto complete quando
rodar o banana -g pegando a sua versão

Em seg, 11 de mar de 2019 11:30, slackjeff <notifications@github.com
escreveu:

**Comment by slackjeff** [comment]
Adicionado na versão 2.1.5.3! Vlw pela sugestão
