### ISSUE TITLE
visual bug on banana install and remove

### ISSUE THREAD

**Issue by linclord** [slackjeff/bananapkg#6]
O banana está exibindo informações incorretas referente ao arquivo .desc durante a instalação e remoção dos pacotes.

`root [ ]# banana -r audacity`
`...`
`[REMOVE] /var/lib/banana/list/audacity-2.3.1-3.desc SUCCESSFULLY`
`[REMOVE] /var/lib/banana/list/audacity-2.3.1-3.list SUCCESSFULLY`

`root [ ]# banana -i audacity-2.3.1-3.mz`
`...`
`[EXTRACT]	 On Your root, OK.`
`[CREATE LIST]	 On /var/lib/banana/list/audacity-2.3.1-3.list`
`[MOVED DESC]	 To /var/lib/banana/audacity-2.3.1-3.desc`
`[INSTALLED]	Package audacity-2.3.1-3 successfully installed.`
`[Clean] List: /var/lib/banana/list/audacity-2.3.1-3.list`

**Comment by slackjeff** [comment]
Opa! Obrigado pelo relato, nestá próxima versão 2.2.4 estará arrumado!
Vou deixar o tópico aberto até o lançamento
