### ISSUE TITLE
Erro ao tentar instalar pacote corrompido

### ISSUE THREAD

**Issue by 4lnx** [slackjeff/bananapkg#8]
bash -x banana -i /var/cache/mz/archives/gtk_engines-2.20.2-2.mz    
+ export PRG=banana
+ PRG=banana
+ export VERSION=2.2
+ VERSION=2.2
+ export format_pkg=mz
+ format_pkg=mz
+ export descme=info/desc
+ descme=info/desc
+ local_list=var/lib/banana/list
+ readonly 'red=\033[31;1m'
+ red='\033[31;1m'
+ readonly 'blue=\033[34;1m'
+ blue='\033[34;1m'
+ readonly 'cyan=\033[36;1m'
+ cyan='\033[36;1m'
+ readonly 'pink=\033[35;1m'
+ pink='\033[35;1m'
+ readonly 'end=\033[m'
+ end='\033[m'
+ source /etc/banana/banana.conf
++ AUTO_YES=0
++ MAINTAINER=
++ BANANA_LANG=default
+ source /usr/libexec/banana/core.sh
+ source /usr/libexec/banana/help.sh
+ dirlist=/var/lib/banana/list
+ dirdesc=/var/lib/banana/desc
+ dirremove=/var/lib/banana/remove
+ [[ 0 -ne 0 ]]
+ [[ default = \p\t\-\b\r ]]
+ HELP=_HELP_US
+ _VERBOSE 0
+ local conf=0
+ [[ '' = \1 ]]
+ [[ 0 = \1 ]]
+ exec
+ for entry_parameter in "$@"
+ [[ -i = \-\y ]]
+ [[ -i = \-\v ]]
+ [[ -i = \-\-\v\e\r\b\o\s\e ]]
+ [[ -i = \-\o\l ]]
+ [[ -i = \-\-\o\n\e\-\l\i\n\e ]]
+ new_argument+=("$entry_parameter")
+ for entry_parameter in "$@"
+ [[ /var/cache/mz/archives/gtk_engines-2.20.2-2.mz = \-\y ]]
+ [[ /var/cache/mz/archives/gtk_engines-2.20.2-2.mz = \-\v ]]
+ [[ /var/cache/mz/archives/gtk_engines-2.20.2-2.mz = \-\-\v\e\r\b\o\s\e ]]
+ [[ /var/cache/mz/archives/gtk_engines-2.20.2-2.mz = \-\o\l ]]
+ [[ /var/cache/mz/archives/gtk_engines-2.20.2-2.mz = \-\-\o\n\e\-\l\i\n\e ]]
+ new_argument+=("$entry_parameter")
+ set -- -i /var/cache/mz/archives/gtk_engines-2.20.2-2.mz
+ case "$1" in
+ shift
+ _INPUT_NULL_PARAMETER /var/cache/mz/archives/gtk_engines-2.20.2-2.mz
+ [[ -z /var/cache/mz/archives/gtk_engines-2.20.2-2.mz ]]
+ [[ -n /var/cache/mz/archives/gtk_engines-2.20.2-2.mz ]]
+ _NAME_FORMAT_PKG /var/cache/mz/archives/gtk_engines-2.20.2-2.mz
+ local packname=/var/cache/mz/archives/gtk_engines-2.20.2-2.mz
+ re='\bmz\b'
+ [[ /var/cache/mz/archives/gtk_engines-2.20.2-2.mz =~ .*\.\bmz\b$ ]]
+ return 0
+ [[ ! -e /var/cache/mz/archives/gtk_engines-2.20.2-2.mz ]]
+ _INSTALL_PKG /var/cache/mz/archives/gtk_engines-2.20.2-2.mz
+ local packname=/var/cache/mz/archives/gtk_engines-2.20.2-2.mz
+ local name_version_build tmp_pack
+ local tmp_pack
+ local PRE_SH=pre.sh
+ pid=22660
+ tar xpmf /var/cache/mz/archives/gtk_engines-2.20.2-2.mz -C /tmp/ ./info/desc
+ _SPINNER
+ spin=('Banana wait' 'bAnana wait' 'baNana wait' 'banAna wait' 'banaNa wait' 'bananA wait' 'banana Wait' 'banana wAit' 'banana waIt' 'banana waiT')
+ :
+ for i in "${spin[@]}"
+ echo -ne '\033[36;1m\rBanana wait\033[m'
Banana wait+ sleep 0.1
tar: This does not look like a tar archive
tar: ./info/desc: Not found in archive
tar: Exiting with failure status due to previous errors
+ echo -e '\033[31;1m[ERROR!]\033[m I could not unzip the file desc.'
[ERROR!] I could not unzip the file desc.
+ exit 1
+ _SUBSHELL_STATUS
+ [[ 1 -ne 0 ]]
+ exit 1
 ✘ ⚡ root@mazonos  /home/dexter33  + for i in "${spin[@]}"

### loop infinito
+ echo -ne '\033[36;1m\rbAnana wait\033[m'
bAnana wait+ sleep 0.1
+ for i in "${spin[@]}"
+ echo -ne '\033[36;1m\rbaNana wait\033[m'

**Comment by slackjeff** [comment]
Obrigado pelo relato! O bug basicamente era que não matava o SPIN que roda em bg! Correção está na próxima versão!

**Comment by 4lnx** [comment]
Por nada, eu que agradeço a atenção.
