### ISSUE TITLE
Error no banana update

### ISSUE THREAD

**Issue by vcatafesta** [slackjeff/bananapkg#9]
# banana update
Internet  [OK]
Cloning into 'bananapkg'...
remote: Enumerating objects: 64, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 412 (delta 37), reused 0 (delta 0), pack-reused 348
Receiving objects: 100% (412/412), 232.41 KiB | 672.00 KiB/s, done.
Resolving deltas: 100% (234/234), done.

Permission and Copy archives

Do you want to overwrite your configuration file? [y/N]
'banana.8' -> '/usr/share/man/pt_BR/man8/banana.8'
'core.sh' -> '/usr/libexec/banana/core.sh'
'help.sh' -> '/usr/libexec/banana/help.sh'
'banana' -> '/sbin/banana'
/sbin/banana: line 235: unexpected EOF while looking for matching `"'
/sbin/banana: line 237: syntax error: unexpected end of file

**Comment by vcatafesta** [comment]
Sugestão: colocar o um exit 0, logo após a atualização deve resolver a questão

**Comment by slackjeff** [comment]
Corrigido, coloquei após a chamada da função... Obrigado pelo report!
